[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "emc2"
version = "0.0.1"
description = "Mixture of Thresholds based Consequentialist Binary Classifier Evaluation"
dependencies = [
    "numpy",
    "scikit-learn",
    "matplotlib"
]